-- 1. Creamos la base de datos y el esquema (si no existen)
CREATE DATABASE IF NOT EXISTS DB_PRUEBA;
CREATE SCHEMA IF NOT EXISTS DB_PRUEBA.TPCH_SF1;

-- 2. Creamos ORDERS con datos solo HASTA 1994
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.ORDERS AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
WHERE O_ORDERDATE < '1995-01-01';

-- 3. Creamos LINEITEM filtrando por la fecha de envío (shipdate) HASTA 1994
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.LINEITEM AS 
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
WHERE L_SHIPDATE < '1995-01-01';

-- 4. Copiamos las tablas maestras íntegras (estas no suelen cambiar)
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.SUPPLIER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.PART     AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.NATION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
CREATE OR REPLACE TABLE DB_PRUEBA.TPCH_SF1.REGION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
-------------------
-- Insertar orders
INSERT INTO DB_PRUEBA.TPCH_SF1.ORDERS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS 
WHERE O_ORDERDATE BETWEEN '1995-01-01' AND '1995-03-31';

-- Insertar sus Líneas de detalle (importante para el JOIN de la capa intermedia)
INSERT INTO DB_PRUEBA.TPCH_SF1.LINEITEM
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM 
WHERE L_ORDERKEY IN (
    SELECT O_ORDERKEY FROM DB_PRUEBA.TPCH_SF1.ORDERS 
    WHERE O_ORDERDATE BETWEEN '1995-01-01' AND '1995-03-31'
);


----------------------- Primer trimestre
-- Insertar orders
INSERT INTO DB_PRUEBA.TPCH_SF1.ORDERS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS 
WHERE O_ORDERDATE BETWEEN '1995-04-01' AND '1995-06-30';

-- Insertar Líneas
INSERT INTO DB_PRUEBA.TPCH_SF1.LINEITEM
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM 
WHERE L_ORDERKEY IN (
    SELECT O_ORDERKEY FROM DB_PRUEBA.TPCH_SF1.ORDERS 
    WHERE O_ORDERDATE BETWEEN '1995-04-01' AND '1995-06-30'
);

---------------------------- Segundo trimestre
INSERT INTO DB_PRUEBA.TPCH_SF1.ORDERS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS 
WHERE O_ORDERDATE BETWEEN '1995-07-01' AND '1995-09-30';

INSERT INTO DB_PRUEBA.TPCH_SF1.LINEITEM
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM 
WHERE L_ORDERKEY IN (SELECT O_ORDERKEY FROM DB_PRUEBA.TPCH_SF1.ORDERS WHERE O_ORDERDATE BETWEEN '1995-07-01' AND '1995-09-30');

------------------------------ Borrar datos para empezar de cero
TRUNCATE TABLE DB_PRUEBA.TPCH_SF1.ORDERS;
TRUNCATE TABLE DB_PRUEBA.TPCH_SF1.LINEITEM;




-- Contar facts antes y despues incremental
SELECT count(*) as total_registros 
FROM DBT_PRUEBAFINAL.dbt_dcarballo.fct_orders;